<script setup lang="ts">
import type { EducationalArticleSection } from '~~/types/api'

/**
 * Part 1 §2 of the Conceptual Document — LLM-generated educational
 * prose (DEC-106, DEC-107). Visually distinct from §1 per DEC-111 so a
 * reader who skims always knows which section is ground-truth lexicon
 * data vs. cited LLM commentary. The distinction is load-bearing.
 *
 * The prose is **rendered, not generated** here. DEC-081 forbids any
 * LLM SDK in the frontend bundle; the prose was generated server-side
 * at concept-creation time and persisted alongside the document.
 */
defineProps<{ section: EducationalArticleSection }>()
</script>

<template>
  <v-card
    color="accent"
    variant="tonal"
    class="pa-6 mb-4"
    data-testid="educational-article-section"
  >
    <div class="d-flex align-center ga-2 mb-3 flex-wrap">
      <v-chip
        size="small"
        color="accent"
        variant="flat"
        prepend-icon="mdi-robot-outline"
        data-testid="educational-article-badge"
      >
        LLM-generated commentary
      </v-chip>
      <v-chip size="small" variant="outlined" prepend-icon="mdi-school-outline">
        educational purposes
      </v-chip>
    </div>

    <v-alert
      type="info"
      variant="tonal"
      density="compact"
      class="mb-4"
      data-testid="educational-article-disclaimer"
    >
      The prose below is LLM-generated educational commentary on the lexicon data above. Treat it as
      a starting prior, not a confirmed claim — the deterministic table in section 1 is the ground
      truth.
    </v-alert>

    <p
      class="text-body-1 mb-3"
      style="white-space: pre-wrap"
      data-testid="educational-article-prose"
    >
      {{ section.prose }}
    </p>

    <p
      v-if="section.model_label"
      class="text-caption text-medium-emphasis mb-1"
      data-testid="educational-article-model"
    >
      Generated by: <code>{{ section.model_label }}</code>
    </p>

    <div v-if="section.cited_sources.length > 0" data-testid="educational-article-sources">
      <p class="text-caption text-medium-emphasis mb-1">Cited sources:</p>
      <ul class="text-caption">
        <li v-for="src in section.cited_sources" :key="src">{{ src }}</li>
      </ul>
    </div>
  </v-card>
</template>
