/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return process-liveness status.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/dsl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Query Dsl
         * @description Accept raw DSL; return validation + result + explanation as JSON.
         */
        post: operations["post_query_dsl_api_v1_query_dsl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/nl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Query Nl
         * @description Accept NL query; compile to DSL via LLM; run pipeline; return JSON.
         */
        post: operations["post_query_nl_api_v1_query_nl_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Capabilities
         * @description Return the MVP capability registry.
         */
        get: operations["get_capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concepts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Concepts
         * @description Return all registered concepts with their lemma lists.
         */
        get: operations["get_concepts_api_v1_concepts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concepts/{name}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Concept Document
         * @description Return the persisted Conceptual Document for ``name``.
         *
         *     404 if no document has been generated for the concept yet (e.g. a curated
         *     seed concept that was never auto-created, or an unknown name). The document
         *     is the deterministic comparative section plus an optional, clearly-labeled
         *     LLM educational section — the article persists, never regenerated per query.
         */
        get: operations["get_concept_document_api_v1_concepts__name__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/query/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Query Validate
         * @description Validate DSL without executing; return the verdict + findings.
         */
        post: operations["post_query_validate_api_v1_query_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlternativeExpr
         * @description A choice between two or more options at a single step position.
         */
        AlternativeExpr: {
            /**
             * Expr Type
             * @default alternative
             * @constant
             */
            expr_type: "alternative";
            /** Options */
            options: (components["schemas"]["NodeRef"] | components["schemas"]["GroupExpr"] | components["schemas"]["AlternativeExpr"] | components["schemas"]["OptionalExpr"])[];
            /**
             * Negated
             * @default false
             */
            negated: boolean;
        };
        /**
         * AlternativeOrderingCount
         * @description Match count for one permutation of the original node sequence.
         *
         *     The original ordering is included in the list with ``is_observed=True``
         *     so consumers can render it alongside its siblings without comparing
         *     permutations themselves. ``permutation`` indices and ``count`` are
         *     schema-enforced non-negative.
         */
        AlternativeOrderingCount: {
            /** Permutation */
            permutation: number[];
            /** Sequence Label */
            sequence_label: string;
            /** Count */
            count: number;
            /** Is Observed */
            is_observed: boolean;
        };
        /**
         * AutoCreatedConceptNote
         * @description Short inline summary surfaced when a query auto-created a Tier-1 concept.
         *
         *     Slice N (DEC-102/DEC-104): when a query references a term with no registry
         *     mapping, the system auto-generates a machine/lexicon-sourced, unverified
         *     concept and re-runs. This note tells the caller it happened, names the
         *     lemmas, and flags that a fuller persisted document is available — so the
         *     auto-creation is never silent (resolved OQ-1: not-silent output).
         */
        AutoCreatedConceptNote: {
            /** Concept Name */
            concept_name: string;
            /** Lemmas */
            lemmas: string[];
            /** Summary */
            summary: string;
            /** Document Available */
            document_available: boolean;
        };
        /**
         * CapabilityRegistry
         * @description Declarative manifest of what the engine currently supports.
         *
         *     Slice L adds two fields that enumerate the executable scope-unit
         *     granularities (``scope_units``) and the maximum cross-verse window in
         *     tokens (``window_max_tokens``). The plain ``scope_fields`` list — which
         *     advertises ``unit`` as a known field — is preserved; ``scope_units``
         *     refines that with the kinds the executor actually runs today.
         */
        CapabilityRegistry: {
            /** Version */
            version: string;
            /** Node Types */
            node_types: string[];
            /** Operators */
            operators: string[];
            /** Match Modes */
            match_modes: string[];
            /** Scope Fields */
            scope_fields: string[];
            /** Scope Units */
            scope_units: string[];
            /** Max Sequence Length */
            max_sequence_length: number;
            /** Max Gap */
            max_gap: number | null;
            /** Window Max Tokens */
            window_max_tokens: number;
            /** Polarity Support */
            polarity_support: boolean;
            /** Inverse Support */
            inverse_support: boolean;
            /** Expansion Support */
            expansion_support: boolean;
            /** Compound Node Support */
            compound_node_support: boolean;
            /** Corpora */
            corpora: string[];
            /** Languages */
            languages: string[];
        };
        /**
         * ClarificationPayload
         * @description Slice L Decision #6: the response payload when the translator emits
         *     a ``Clarification:`` instead of ``DSL:``.
         *
         *     The route returns a 200 with this set and the other fields (``result``,
         *     ``validation``, ``explanation``, ``translation``) absent. No query
         *     executed. The frontend (follow-up scope) renders the question + the
         *     suggested windows as a choice surface.
         */
        ClarificationPayload: {
            /** Question */
            question: string;
            /** Suggested Windows */
            suggested_windows: number[];
            /** Nl Source */
            nl_source: string;
        };
        /**
         * ComparativeLexiconSection
         * @description Part 1 §1 — pure comparative lexicon analysis. NO LLM, no opinion.
         */
        ComparativeLexiconSection: {
            /** English Term */
            english_term: string;
            /** Rows */
            rows: components["schemas"]["LexiconComparisonRow"][];
            /** Generated From */
            generated_from: string[];
        };
        /**
         * ConceptDocument
         * @description The persisted two-part Conceptual Document.
         *
         *   Part 2 (Tier-2 grouping) takes one of three shapes (Slice O):
         *     * part2_grouping — full Tier2Grouping on the anchor concept's doc
         *     * part2_grouping_pointer — GroupingPointer on a member concept's doc
         *     * both null — concept not yet a member of any grouping
         */
        ConceptDocument: {
            /** Concept Name */
            concept_name: string;
            /** Short Summary */
            short_summary: string;
            part1_comparative: components["schemas"]["ComparativeLexiconSection"];
            part1_educational?: components["schemas"]["EducationalArticleSection"] | null;
            part2_grouping?: components["schemas"]["Tier2Grouping"] | null;
            part2_grouping_pointer?: components["schemas"]["GroupingPointer"] | null;
        };
        /**
         * GroupingMember
         * @description One member of a Tier-2 grouping with its per-edge confidence.
         */
        GroupingMember: {
            /** Concept Name */
            concept_name: string;
            /** Confidence */
            confidence: number;
            /** Note */
            note?: string | null;
        };
        /**
         * GroupingPointer
         * @description Pointer stored on a non-anchor member's document, listing the
         *     anchor concept(s) whose document carries the canonical grouping blob.
         */
        GroupingPointer: {
            /** Grouping Anchors */
            grouping_anchors: string[];
        };
        /**
         * Tier2Grouping
         * @description Persisted Tier-2 grouping claim. ALWAYS verification_state='unverified'
         *     (DEC-081 / DEC-115 runtime guard).
         */
        Tier2Grouping: {
            /** Anchor Name */
            anchor_name: string;
            /** Members */
            members: components["schemas"]["GroupingMember"][];
            /** Rationale */
            rationale: string;
            /** Origin */
            origin?: "curated" | "ai_suggested";
            /** Verification State */
            verification_state?: "unverified";
            /** Created At */
            created_at: string;
        };
        /**
         * ConceptSummary
         * @description Aggregate view of a concept + its lemma list, used by the HTTP layer
         *     to render the seeded registry without a second round-trip per concept.
         *
         *     `lemma_count` is redundant with `len(lemmas)` — kept as a separate field
         *     so UI clients can render counts without traversing the array.
         */
        ConceptSummary: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Verification State
             * @default unverified
             * @enum {string}
             */
            verification_state: "unverified" | "corpus_observed" | "human_confirmed";
            /**
             * Lemma Count
             * @default 0
             */
            lemma_count: number;
            /**
             * Lemmas
             * @default []
             */
            lemmas: string[];
        };
        /**
         * ConceptsResponse
         * @description Response body for GET /api/v1/concepts.
         *
         *     Contains the seeded registry's concepts with embedded lemma lists per
         *     DEC-076 (no pagination at MVP scale; revisit when registry grows past
         *     Bucket 9's trigger).
         */
        ConceptsResponse: {
            /** Concepts */
            concepts: components["schemas"]["ConceptSummary"][];
        };
        /**
         * Contextualization
         * @description Calibration envelope for a single result set.
         *
         *     Per canonical-09 §8: contextualization runs after retrieval, before
         *     scoring. It does not modify per-match scores; it calibrates the result
         *     set as a whole against constituent-node baselines and sibling permutations.
         */
        Contextualization: {
            /** Observed Count */
            observed_count: number;
            /** Node Baselines */
            node_baselines: components["schemas"]["NodeBaseline"][];
            /** Alternative Orderings */
            alternative_orderings: components["schemas"]["AlternativeOrderingCount"][];
            /** Alternative Orderings Capped */
            alternative_orderings_capped: boolean;
            null_distribution?: components["schemas"]["NullDistribution"] | null;
        };
        /**
         * ConversationTurn
         * @description One turn of a refinement conversation, echoed back by the client each
         *     request per the stateless-echo-back design (DEC-098).
         */
        ConversationTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /**
         * EducationalArticleSection
         * @description Part 1 §2 — LLM-generated educational analysis (built in src/nlp).
         *
         *     Stored WITH its citations and a generated label. Mirrored here so the
         *     document entity can carry it; this module never CONSTRUCTS it.
         */
        EducationalArticleSection: {
            /** Prose */
            prose: string;
            /** Cited Sources */
            cited_sources: string[];
            /**
             * Generated
             * @default true
             */
            generated: boolean;
            /** Model Label */
            model_label: string;
        };
        /**
         * ExpansionDirection
         * @description Directions for expansion directives.
         * @enum {string}
         */
        ExpansionDirection: "forward" | "backward" | "both";
        /**
         * ExpansionDirective
         * @description Instructs the engine to explore beyond the stated sequence.
         */
        ExpansionDirective: {
            direction: components["schemas"]["ExpansionDirection"];
            /** Depth */
            depth: number;
        };
        /** ExplainedResult */
        ExplainedResult: {
            /** Reference */
            reference: string;
            /** Text Display */
            text_display: string;
            /**
             * Match Type
             * @enum {string}
             */
            match_type: "exact" | "variant" | "conceptual";
            /** Score */
            score?: number | null;
            /** Explanation */
            explanation: string;
            proximity?: components["schemas"]["ProximityInfo"] | null;
        };
        /** ExplainedResultSet */
        ExplainedResultSet: {
            /** Query Shown */
            query_shown: string;
            /** Nl Source */
            nl_source?: string | null;
            /** Validation Notes */
            validation_notes: string[];
            /** Results */
            results: components["schemas"]["ExplainedResult"][];
            contextualization?: components["schemas"]["Contextualization"] | null;
            /** Summary */
            summary: string;
        };
        /**
         * GapConstraint
         * @description Limits the token distance between two sequence steps.
         */
        GapConstraint: {
            /**
             * Min
             * @default 0
             */
            min: number;
            /** Max */
            max?: number | null;
        };
        /**
         * GroupExpr
         * @description A parenthesized sub-sequence treated as a single step.
         */
        GroupExpr: {
            /**
             * Expr Type
             * @default group
             * @constant
             */
            expr_type: "group";
            sequence: components["schemas"]["SequenceExpr"];
            /**
             * Negated
             * @default false
             */
            negated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InverseExpr
         * @description Wraps a sequence for inverse-pole resolution at execution time.
         */
        InverseExpr: {
            inner: components["schemas"]["SequenceExpr"];
        };
        /**
         * LexiconComparisonRow
         * @description One row of the deterministic comparative table: a lemma and its data.
         */
        LexiconComparisonRow: {
            /** Lemma */
            lemma: string;
            /** Strongs */
            strongs: string[];
            /** Usual Renderings */
            usual_renderings: string[];
            /** Corpus Verse Refs */
            corpus_verse_refs: string[];
        };
        /**
         * MatchCandidate
         * @description One verse-grouped candidate produced by ``execute()``.
         *
         *     Per canonical-09 §5: ``tokens`` is the ordered list of matched tokens,
         *     ``reference`` is the human-readable verse pointer (``"1Cor 13:13"``),
         *     ``match_type`` distinguishes exact / variant / conceptual (DEC-007), and
         *     ``alignment`` carries the per-step provenance.
         *
         *     Slice L: ``proximity`` carries a :class:`ProximityInfo` envelope when the
         *     candidate was produced by a ``ScopeUnitWindow(n)`` query; ``None`` for
         *     verse-scope candidates. The ``match_type`` axis (how it matched) and the
         *     ``proximity`` axis (where it landed) are orthogonal — Decision #4.
         */
        MatchCandidate: {
            /** Tokens */
            tokens: components["schemas"]["MatchedToken"][];
            /** Reference */
            reference: string;
            /**
             * Match Type
             * @enum {string}
             */
            match_type: "exact" | "variant" | "conceptual";
            /** Alignment */
            alignment: components["schemas"]["StepMatch"][];
            proximity?: components["schemas"]["ProximityInfo"] | null;
        };
        /**
         * MatchedToken
         * @description A token row projection used in executor results.
         *
         *     Intentionally drops ``morph_code``, ``language``, and ``corpus_id`` from
         *     the underlying ``tokens`` row (decision #3 in
         *     ``thoughts/design-pattern-engine-executor-2026-05-09.md``). MVP does not
         *     need them and the extra fields invite premature feature scope.
         */
        MatchedToken: {
            /** Id */
            id: number;
            /** Book */
            book: string;
            /** Chapter */
            chapter: number;
            /** Verse */
            verse: number;
            /** Position */
            position: number;
            /** Global Position */
            global_position: number;
            /** Surface Form */
            surface_form: string;
            /** Normalized Form */
            normalized_form: string;
            /** Lemma */
            lemma: string;
            /** Pos */
            pos: string;
        };
        /**
         * MorphFilter
         * @description A morphological feature filter (e.g., NOUN, VERB, IMPERATIVE).
         */
        MorphFilter: {
            /** Feature */
            feature: string;
        };
        /**
         * NodeBaseline
         * @description How often a single constituent node fires alone in the scoped corpus.
         *
         *     Lemma nodes resolve to themselves; concept nodes resolve to all lemmas in
         *     the registry mapping (per REQ:04.matching-rules). ``count`` is a scoped
         *     SELECT COUNT(*) against the tokens table; ``node_index`` is the 0-based
         *     position in the original sequence — both non-negative invariants are
         *     encoded in the schema (Codex D-D1D2-002).
         */
        NodeBaseline: {
            /** Node Index */
            node_index: number;
            node_type: components["schemas"]["NodeType"];
            /** Node Value */
            node_value: string;
            /** Resolved Lemmas */
            resolved_lemmas: string[];
            /** Count */
            count: number;
        };
        /**
         * NodeRef
         * @description A typed reference to a node in the ontology.
         */
        NodeRef: {
            /**
             * Expr Type
             * @default node_ref
             * @constant
             */
            expr_type: "node_ref";
            type: components["schemas"]["NodeType"];
            /** Value */
            value: string;
            /** Polarity */
            polarity?: ("+" | "-" | "±") | null;
            /**
             * Morph Filters
             * @default []
             */
            morph_filters: components["schemas"]["MorphFilter"][];
            /**
             * Negated
             * @default false
             */
            negated: boolean;
        };
        /**
         * NodeType
         * @description Node types from the ontology (docs/canonical/04_node-ontology.md).
         * @enum {string}
         */
        NodeType: "token" | "lemma" | "root" | "concept" | "domain" | "morph" | "wildcard";
        /**
         * NullDistribution
         * @description Sampling-based null baseline.
         *
         *     MVP reserves the schema slot but never populates it (per design OQ #3
         *     resolution: the sampling protocol needs its own design pass — what
         *     counts as a "comparable-frequency" lemma, how comparability is defined,
         *     and how the seed propagates). Exposed as ``Contextualization.null_distribution``;
         *     always ``None`` until a future slice ships the sampling code. ``mean``
         *     is unconstrained (counts can have any non-negative mean but allowing
         *     floats here keeps the schema flexible for future computed statistics);
         *     ``sample_size`` and ``std`` are schema-enforced non-negative.
         */
        NullDistribution: {
            /** Sample Size */
            sample_size: number;
            /** Mean */
            mean: number;
            /** Std */
            std: number;
            /** Seed */
            seed: number;
        };
        /**
         * OperatorType
         * @description Order operators between sequence steps.
         * @enum {string}
         */
        OperatorType: "precedence" | "adjacency" | "cooccurrence";
        /**
         * OptionalExpr
         * @description A step that may or may not be present in a match.
         */
        OptionalExpr: {
            /**
             * Expr Type
             * @default optional
             * @constant
             */
            expr_type: "optional";
            /** Inner */
            inner: components["schemas"]["NodeRef"] | components["schemas"]["GroupExpr"] | components["schemas"]["AlternativeExpr"] | components["schemas"]["OptionalExpr"];
        };
        /**
         * OrderOperator
         * @description Defines the relationship between adjacent steps in a sequence.
         */
        OrderOperator: {
            type: components["schemas"]["OperatorType"];
            gap?: components["schemas"]["GapConstraint"] | null;
        };
        /**
         * ProximityInfo
         * @description Cross-verse proximity envelope attached to a ``MatchCandidate`` produced
         *     by a ``ScopeUnitWindow(n)`` query (Slice L Decision #4).
         *
         *     Layered onto the existing ``match_type`` axis — a conceptual hit at
         *     ``window=50`` is ``match_type="conceptual"`` AND
         *     ``proximity=ProximityInfo(window_n=50, …)``. ``None`` on verse-scope
         *     queries.
         *
         *     Carries the full window's tokens (matched + non-matched) so consumers can
         *     inspect the "scaffolding" — what else appeared between the matches.
         *     ``intervening_lemmas`` is capped at the top 20 by count (Decision #9);
         *     the remaining tail is summed into ``other_count``.
         */
        ProximityInfo: {
            /** Window N */
            window_n: number;
            /** Span Tokens */
            span_tokens: number;
            /** Crosses Verse */
            crosses_verse: boolean;
            /** Crosses Chapter */
            crosses_chapter: boolean;
            /** Window Tokens */
            window_tokens: components["schemas"]["MatchedToken"][];
            /** Intervening Lemmas */
            intervening_lemmas: {
                [key: string]: number;
            };
            /**
             * Other Count
             * @default 0
             */
            other_count: number;
        };
        /**
         * QueryDSLRequest
         * @description Request body for POST /api/v1/query/dsl.
         */
        QueryDSLRequest: {
            /** Dsl */
            dsl: string;
        };
        /**
         * QueryDSLResponse
         * @description Response envelope: query echo + validation + result + explanation.
         *
         *     Always emits the four pipeline fields. `auto_created_concept` is set only
         *     when this query triggered a Tier-1 concept auto-creation (Slice N); None
         *     otherwise. The CLI's `--no-prose` affordance is a CLI concept; service-layer
         *     consumers who want raw counts read `result` and ignore `explanation.summary`.
         */
        QueryDSLResponse: {
            /** Query */
            query: string;
            validation: components["schemas"]["ValidationResult"];
            result: components["schemas"]["RetrievalResult"];
            explanation: components["schemas"]["ExplainedResultSet"];
            auto_created_concept?: components["schemas"]["AutoCreatedConceptNote"] | null;
        };
        /**
         * QueryMetadata
         * @description Metadata attached to a compiled query plan.
         */
        QueryMetadata: {
            /** Nl Source */
            nl_source?: string | null;
            /** Parse Timestamp */
            parse_timestamp?: string | null;
        };
        /**
         * QueryNLRequest
         * @description Request body for POST /api/v1/query/nl.
         */
        QueryNLRequest: {
            /** Nl Query */
            nl_query: string;
            /** Prior Turns */
            prior_turns?: components["schemas"]["ConversationTurn"][];
        };
        /**
         * QueryNLResponse
         * @description Response envelope for POST /api/v1/query/nl.
         *
         *     Two shapes (Slice L Decision #6):
         *     - Executed: ``query`` (compiled DSL) + ``validation`` + ``result`` +
         *       ``explanation`` + ``translation`` populated; ``clarification`` is None.
         *     - Clarification: ``query`` (the original NL) + ``clarification``
         *       populated; the four pipeline fields are None.
         *
         *     The discriminating signal is presence/absence of ``clarification``.
         *     Always returned as HTTP 200.
         */
        QueryNLResponse: {
            /** Query */
            query: string;
            validation?: components["schemas"]["ValidationResult"] | null;
            result?: components["schemas"]["RetrievalResult"] | null;
            explanation?: components["schemas"]["ExplainedResultSet"] | null;
            translation?: components["schemas"]["TranslationMetadata"] | null;
            clarification?: components["schemas"]["ClarificationPayload"] | null;
            auto_created_concept?: components["schemas"]["AutoCreatedConceptNote"] | null;
        };
        /**
         * QueryPlan
         * @description Top-level compiled query — the contract between parser and engine.
         */
        QueryPlan: {
            /** Version */
            version: string;
            /** Source */
            source: string;
            /** Sequence */
            sequence: components["schemas"]["SequenceExpr"] | components["schemas"]["InverseExpr"];
            scope: components["schemas"]["ScopeConstraint"];
            /**
             * Mode
             * @enum {string}
             */
            mode: "exact" | "variant" | "conceptual" | "hybrid";
            expansion?: components["schemas"]["ExpansionDirective"] | null;
            ranking?: components["schemas"]["RankingPrefs"] | null;
            /** @default {} */
            metadata: components["schemas"]["QueryMetadata"];
        };
        /**
         * QueryValidateRequest
         * @description Request body for POST /api/v1/query/validate.
         */
        QueryValidateRequest: {
            /** Dsl */
            dsl: string;
        };
        /**
         * QueryValidateResponse
         * @description Response body for POST /api/v1/query/validate.
         *
         *     Mirrors `QueryDSLResponse` shape (echoes the input + carries
         *     structured output) but omits `result` and `explanation` — the
         *     /validate path does not execute the engine. Per DEC-079, all
         *     `validation.status` values (supported/partial/unsupported) return
         *     HTTP 200; the only 422 path on this route is `parse_error` raised
         *     on malformed DSL.
         */
        QueryValidateResponse: {
            /** Query */
            query: string;
            validation: components["schemas"]["ValidationResult"];
        };
        /**
         * RankingFactor
         * @description Factors for scoring and ranking matches.
         * @enum {string}
         */
        RankingFactor: "lexical_alignment" | "morphology_alignment" | "semantic_overlap" | "polarity_fidelity" | "rarity" | "contextual_coherence";
        /**
         * RankingPrefs
         * @description User-specified ranking weight preferences.
         */
        RankingPrefs: {
            /** Weights */
            weights: {
                [key: string]: number;
            };
        };
        /**
         * RetrievalResult
         * @description Top-level envelope returned by ``retrieve()``.
         *
         *     Per canonical-09 §6. ``contextualization`` is populated only when the
         *     caller requested it (engine-layer default ``False``; CLI/API default
         *     ``True`` per OQ #1 middle-path resolution).
         */
        RetrievalResult: {
            /** Candidates */
            candidates: components["schemas"]["MatchCandidate"][];
            /** Stages Used */
            stages_used: string[];
            contextualization?: components["schemas"]["Contextualization"] | null;
        };
        /**
         * ScopeConstraint
         * @description Search boundaries for a query.
         */
        ScopeConstraint: {
            /** Corpus */
            corpus?: string | null;
            /** Language */
            language?: string | null;
            /** Books */
            books?: string[] | null;
            /** Unit */
            unit?: (components["schemas"]["ScopeUnitVerse"] | components["schemas"]["ScopeUnitWindow"]) | null;
        };
        /**
         * ScopeUnitVerse
         * @description Single-verse scope (legacy MVP unit; default when ``unit is None``).
         */
        ScopeUnitVerse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "verse";
        };
        /**
         * ScopeUnitWindow
         * @description Cross-verse window of ``n`` tokens, anchored on the first match's
         *     ``global_position``. Book boundary blocked; chapter boundary crossable
         *     (Decision #3). ``n == 0`` is rejected at parse time (Decision #8); the
         *     capability validator emits ``WINDOW_EXCEEDS_MAX`` when ``n`` exceeds
         *     ``CapabilityRegistry.window_max_tokens`` (Decision #5).
         */
        ScopeUnitWindow: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "window";
            /** N */
            n: number;
        };
        /**
         * SequenceExpr
         * @description An ordered list of steps with operators between them.
         */
        SequenceExpr: {
            /** Steps */
            steps: (components["schemas"]["NodeRef"] | components["schemas"]["GroupExpr"] | components["schemas"]["AlternativeExpr"] | components["schemas"]["OptionalExpr"])[];
            /** Operators */
            operators: components["schemas"]["OrderOperator"][];
        };
        /**
         * StepMatch
         * @description How one DSL step lined up with one matched token.
         */
        StepMatch: {
            /** Step Index */
            step_index: number;
            node_type: components["schemas"]["NodeType"];
            /** Node Value */
            node_value: string;
            /** Resolved Lemmas */
            resolved_lemmas: string[];
            token: components["schemas"]["MatchedToken"];
        };
        /**
         * TranslationMetadata
         * @description Translator-side metadata surfaced on the NL response envelope.
         *
         *     Sibling to the DSL pipeline's existing fields. `confidence` and
         *     `alternatives` come from the translator (DEC-072: not used to gate
         *     execution; surfaced for the caller to decide). `explanation` is the
         *     translator's prose justification, distinct from the result-side
         *     `ExplainedResultSet.summary`.
         */
        TranslationMetadata: {
            /** Confidence */
            confidence: number;
            /** Alternatives */
            alternatives: string[];
            /** Explanation */
            explanation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ValidationFinding
         * @description One specific capability gap or concern.
         */
        ValidationFinding: {
            /**
             * Severity
             * @enum {string}
             */
            severity: "error" | "warning" | "info";
            /** Code */
            code: string;
            /** Path */
            path: string;
            /** Message */
            message: string;
            /** Remediation */
            remediation?: string | null;
        };
        /**
         * ValidationResult
         * @description Result of validating a QueryPlan against the capability registry.
         *
         *     The optional ``grounding`` axis (REQ:08.registry-epistemics, decision #6)
         *     is orthogonal to ``status`` and ``match_mode``: it answers "is the
         *     resolution backed by corpus evidence" for any concept-registry-backed
         *     nodes in the plan. ``None`` means rule 13 was not run (no
         *     ``concept_registry`` was passed) or no concept nodes were inspected.
         */
        ValidationResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "partial" | "unsupported";
            executable_plan: components["schemas"]["QueryPlan"] | null;
            /** Findings */
            findings: components["schemas"]["ValidationFinding"][];
            /** Engine Version */
            engine_version: string;
            /** Grounding */
            grounding?: ("evidence-grounded" | "prior-grounded" | "mixed") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    post_query_dsl_api_v1_query_dsl_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryDSLRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryDSLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_query_nl_api_v1_query_nl_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryNLRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryNLResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityRegistry"];
                };
            };
        };
    };
    get_concepts_api_v1_concepts_get: {
        parameters: {
            query?: {
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_concept_document_api_v1_concepts__name__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_query_validate_api_v1_query_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
