/**
 * Backend response types.
 *
 * THIS FILE IS A PLACEHOLDER. The canonical version is generated by
 * `npm run gen:types`, which fetches `$NUXT_BACKEND_URL/openapi.json`
 * via `openapi-typescript` and writes the result here. Until the
 * backend is deployed and the bootstrap runbook has been executed,
 * these hand-written types stand in.
 *
 * Once generated, the file's shape changes to the `openapi-typescript`
 * `paths` + `components` form. Component code should migrate to
 * `import type { components } from '~~/types/backend'`
 * and reference `components['schemas']['QueryNLResponse']` etc.
 *
 * For now, the components use the named interfaces below directly.
 * The shapes match `src/app/schemas.py` + `src/engine/models.py` +
 * `src/validation/validator.py` in the backend repo at the time this
 * file was written.
 *
 * DEC-081 enforcement: when this file is regenerated, the structural
 * seam locks the frontend to the backend's declared response shape.
 */

export type MatchType = 'exact' | 'variant' | 'conceptual'

export type ValidationStatus = 'supported' | 'partial' | 'unsupported'

export interface ValidationFinding {
  severity: 'error' | 'warning' | 'info'
  code: string
  path: string
  message: string
  remediation: string | null
}

export interface ValidationResult {
  status: ValidationStatus
  executable_plan: unknown | null
  findings: ValidationFinding[]
  engine_version: string
  grounding: 'evidence-grounded' | 'prior-grounded' | 'mixed' | null
}

export interface MatchedToken {
  // Shape varies by token type; the frontend renders `text_display` from
  // ExplainedResult rather than introspecting tokens.
  [k: string]: unknown
}

export interface StepMatch {
  [k: string]: unknown
}

export interface MatchCandidate {
  tokens: MatchedToken[]
  reference: string
  match_type: MatchType
  alignment: StepMatch[]
}

export interface NodeBaseline {
  node_index: number
  value: string
  resolved_lemmas: string[]
  count: number
  match_type: MatchType
  sample_size: number
}

export interface AlternativeOrderingCount {
  sequence_label: string
  count: number
  is_observed: boolean
}

export interface NullDistribution {
  mean: number
  std: number
  observed_count: number
  permutations: number[]
}

export interface Contextualization {
  observed_count: number
  node_baselines: NodeBaseline[]
  alternative_orderings: AlternativeOrderingCount[]
  null_distribution: NullDistribution | null
}

export interface RetrievalResult {
  candidates: MatchCandidate[]
  stages_used: string[]
  contextualization: Contextualization | null
}

export interface ExplainedResult {
  reference: string
  text_display: string
  match_type: MatchType
  score: number | null
  explanation: string
}

export interface ExplainedResultSet {
  query_shown: string
  nl_source: string | null
  validation_notes: string[]
  results: ExplainedResult[]
  contextualization: Contextualization | null
  summary: string
}

export interface TranslationMetadata {
  confidence: number
  alternatives: string[]
  explanation: string
}

export interface QueryNLResponse {
  query: string
  validation: ValidationResult
  result: RetrievalResult
  explanation: ExplainedResultSet
  translation: TranslationMetadata
}

export interface ErrorResponseDetail {
  error: string
  message: string
  details: Record<string, unknown> | null
}

export interface BackendErrorBody {
  detail?: ErrorResponseDetail
}
